name: guv_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scikit-image
  - mplcursors
  - scipy
  - opencv
  - pandas
  - tqdm
  - matplotlib
  - colorama
  - seaborn
  - pytables
  - h5py
  - nd2reader
  - pip
  - pip:
    - napari
    - PyQt5


